CHANGELOG.rst
README.rst
pytest_subtests.py
tests/test_subtests.py

Add support for --pdb in subtests

---

CHANGELOG.rst
pytest_subtests.py
tests/test_subtests.py

This change ensures that all `makereport` hooks get called prior to
subtests transforming the constructed `TestReport` to a `SubTestReport`.
A test is added for pytest style usage and an xfailing test is added for
unittest style since the same issue affecting skip counting is present
for xfail counting.
Fixes #24

fix: Allow subtests to xfail

---

README.rst

I needed to include the module of the warning in the pytest config or else I got a `warnings._OptionError: unknown warning category: 'PytestDeprecationWarning'` error. With this change, the warning is properly ignored.

Fix readme warnings suggestion

---

pytest_subtests.py
tests/test_subtests.py

Use "SUBPASS" and "," for passed subtests instead of general "PASSED",
"SUBFAIL" and "u" for failed ones instead of "FAILED".

Explicit hint to subtests in progress and summary

---

.github/workflows/deploy.yml
.github/workflows/main.yml
CHANGELOG.rst
pytest_subtests.py
setup.py

- Add support (and require) pytest 7.0
- Separate deploy stop in CI
Close #38

Release 0.7.0

---

CHANGELOG.rst
pytest_subtests.py
tests/test_subtests.py

This does not alter the handling of skipped/failing tests, which aggregate alongside the normal test counts.
Previously we didn't count passing subtests in any totals to match unittest's behavior.
I don't love this solution as the inconsistency between the counting of passed vs skipped/failed is very odd to me, but if matching unittest is a requirement then this will serve 😄 
fixes #39

count passing subtests separately and show them in final summary

---

.github/workflows/main.yml
CHANGELOG.rst
pytest_subtests.py
setup.py
tox.ini

py3.6 is now deprecated, and not supported in pytest either

Drop support for python 3.6

---

.github/workflows/main.yml
tests/test_subtests.py
tox.ini

Closes https://github.com/pytest-dev/pytest-subtests/issues/69
In py3.11, the full test name now shows up. See https://github.com/python/cpython/pull/32138
Not sure if there's a better way to do this, I was hoping to do `(__main__.T*)` but that doesn't seem to play well with `fnmatch_lines`

py3.11 compatibility for tests

---

tox.ini

```
py37: failed with pass_env values cannot contain whitespace, use comma to have multiple values in a single line, invalid values found 'USER USERNAME TRAVIS PYTEST_ADDOPTS'
```

Fix tox 4 error

---

CHANGELOG.rst
pytest_subtests.py

This allows the native pytest column calculations to not be disrupted and minimizes unneeded output for large CI systems.
This recomputes the correct output for every test. I'm not sure if that's a significant performance impact (probably not), but if there's a better way to memoize it let me know and I'll be happy to change it.

add an option to disable shortletter output

---

.github/workflows/deploy.yml

The `master` branch has been deprecated for quite a while and is way out-of-date. `release/v1` corresponds to the stable API.
Also, `__token__` has always been the default username so it's not needed either.

Update `pypa/gh-action-pypi-publish` to `release/v1`

---

CHANGELOG.rst
pytest_subtests.py
tests/test_subtests.py
tox.ini

Passing subtests no longer turn the output yellow (similar to warnings)

---

.github/workflows/deploy.yml
.github/workflows/test.yml
.gitignore
RELEASING.rst

* Create the package first, and test on all platforms using it.
* Deploy is now manually triggered, and requires approvals.

Improve deploy workflow and testing

---

.github/workflows/test.yml
.pre-commit-config.yaml
CHANGELOG.rst
pyproject.toml
setup.cfg
src/pytest_subtests/plugin.py
tests/test_subtests.py
tox.ini

Run static type checking with Mypy

---

README.rst

Hi,
I noticed that the PyPI link in the README was linking to a 404 page.
I opted to link to the project page itself, rather than the PyPI homepage since it seemed more useful.

Fixed link to PyPI in README

---

CHANGELOG.rst
src/pytest_subtests/plugin.py

Fix compatibility with pytest 8.1

---

CHANGELOG.rst
src/pytest_subtests/plugin.py

Does the same as described in https://docs.pytest.org/en/7.1.x/example/simple.html#writing-well-integrated-assertion-helpers.
Will certainly help with reading what failed in subtests ran from `runpy.run_path()`.
Here's an example for [lazy_importing](https://github.com/bswck/lazy_importing) with [quite unusual test setup](https://github.com/bswck/lazy_importing/blob/main/tests).
**Before**
<details>
```
(lazy-importing-py3.8) ~/dev/lazy_importing git:(main|✚3)❯❯❯ pytest . -svvvv
Test session starts (platform: linux, Python 3.8.19, pytest 8.1.1, pytest-sugar 1.0.0)
cachedir: .pytest_cache
rootdir: /home/bswck/dev/lazy_importing
configfile: pyproject.toml
plugins: sugar-1.0.0, doctestplus-1.2.1, subtests-0.12.1, anyio-4.3.0
collected 1 item …
```

Hide `SubTests.test()` from tracebacks

---

CHANGELOG.rst
src/pytest_subtests/plugin.py
tests/test_subtests.py

Attempts to progress on https://github.com/pytest-dev/pytest-subtests/issues/23.  Submitting as a draft to see if I can get some advice.  
Summary: Support for `pytest -x` to stop after the first failing subtest.  The implementation here does stop after the first failing subtest, however it also:
1.  Marks the parent test as a failure 
b/c
2. The `session.Failed` exception raised from inside the `subtests.test` is treated as an uncaught exception from within the test.  This results in the stack trace printed pointing to `contextlib` which feels undesirable to me.
I think the behavior in (1) is debatable.  On one hand - a failing subtest does not by default fail the parent test.  On the other hand, by design the parent test will not complete.  In either case, (2) I think would be really …

Support -x to fail fast

---

CHANGELOG.rst
src/pytest_subtests/plugin.py
tests/test_subtests.py

In https://github.com/pytest-dev/pytest-subtests/pull/134 support was added for `--exitfirst`.  I think we might have an off by one error, this PR just illustrating with this small change to the tests.
I think the issue is that `self.request.session.shouldfail` does not get set until we call `pytest_runtest_logreport` which is after the flag is checked.  The result is the tests get stopped after the *2nd* failing subtest instead of the first.

Fix potential off by one error

---

CHANGELOG.rst
src/pytest_subtests/plugin.py
tests/test_subtests.py
tox.ini

Currently, the reporting has issues in the cases where `skipTest` is used inside `subTest`. For example
```python
import unittest
class T(unittest.TestCase):
def test_foo(self):
for i in range(10):
with self.subTest("custom message", i=i):
if i < 4:
self.skipTest(f"skip {i}")
assert i < 4
```
outputs
```bash
tests/test_foo.py::T::test_foo [custom message] (i=4) SUBSKIP (skip 0)
tests/test_foo.py::T::test_foo [custom message] (i=5) SUBSKIP (skip 1)
tests/test_foo.py::T::test_foo [custom message] (i=6) SUBSKIP (skip 2)
tests/test_foo.py::T::test_foo [custom message] (i=7) SUBSKIP (skip 3)
tests/test_foo.py::T::test_foo [custom message] (i=8) SUBFAIL
tests/test_foo.py::T::test_foo [custom message] (i=9) SUBFAIL
tests/test_foo.py::T::test_foo PASSED
...
=============== short test summary info …
```

Fix `skipTest` inside `subTest`

---

CHANGELOG.rst
src/pytest_subtests/plugin.py
tests/test_subtests.py

Fix #173.
When a test is decorated with `unittest.skip`, `self.instance._outcome` would be `None` and we need to take this into account.

Fix `self.instance._outcome` is `None` case in #173

---

tests/test_subtests.py

Fixes #176.
Not all of the strings that I changed to raw literals (`r""`) contain invalid escape sequences like `\(`, but it makes sense (and is less error-prone) to use raw literals for regex patterns across the board rather than picking and choosing based on the contents of the patterns.

Consistently use raw strings for line-matching regexes

---

.github/workflows/test.yml
tests/test_subtests.py
tox.ini

Ensure advertised pytest 7.4 compatibility

---

CHANGELOG.rst
src/pytest_subtests/plugin.py
tests/test_subtests.py

See https://github.com/pytest-dev/pytest-subtests/issues/198.

Add `--no-subtest-reports` CLI opt
